version: '3'

tasks:
  dev:
    cmds:
      - npm run dev

  build:
    cmds:
      - npm run build

  lint:
    cmds:
      - npm run lint

  list:
    cmds:
      - task --list-all

  install-all:
    cmds:
      - npm install

  reinstall-all:
    cmds:
      - rm -rf ./node_modules
      - task: install-all

  connect-db:
    cmds:
      - pscale connect carrot-market

  prisma-push:
    cmds:
      - npx prisma db push

  prisma-studio:
    cmds:
      - npx prisma studio